const types = {
  SET_CUSTOMER: '@shop/SET_CUSTOMER',
  REQUEST_MARKETS: '@shop/REQUEST_MARKETS',
  SET_MARKETS: '@shop/SET_MARKETS',
  SET_MARKET_MAP_SELECTED: '@shop/SET_MARKET_MAP_SELECTED',
  SET_MAP_CENTER: '@shop/SET_MAP_CENTER',
  REQUEST_MARKET: '@shop/REQUEST_MARKET',
  SET_PETSHOP: '@shop/SET_MARKET',
  TOGGLE_CART_PRODUCT: '@shop/TOGGLE_CART_PRODUCT'
}

export default types;
